/* Script generated by Pawn Studio */

#include <amxmodx>
#include <amxmisc>
#include <fun>
#include <jbsam>

new cvar_can_parasi
new canesya

public plugin_init()
{
	register_plugin("JB-SAM : Can Alma","1.0","Yek'-ta")
	cvar_can_parasi = register_cvar("jbsam_can_ucret","16000")
	canesya = jbsam_esya_gir("+50 Can", get_pcvar_num(cvar_can_parasi), "Ek olarak 50 Can Alirsin", GARDIYAN)
}

public jbsam_esya_sec(id, item){
	if(item != canesya)
		return PLUGIN_HANDLED

	set_user_health(id, get_user_health(id) + 50)

	return PLUGIN_CONTINUE
}
